#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pesign
Version  : 113
Release  : 11
URL      : https://github.com/rhboot/pesign/releases/download/113/pesign-113.tar.bz2
Source0  : https://github.com/rhboot/pesign/releases/download/113/pesign-113.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: pesign-bin = %{version}-%{release}
Requires: pesign-libexec = %{version}-%{release}
Requires: pesign-license = %{version}-%{release}
Requires: pesign-man = %{version}-%{release}
BuildRequires : nspr-dev
BuildRequires : pkgconfig(efivar)
BuildRequires : pkgconfig(nss)
BuildRequires : pkgconfig(popt)
BuildRequires : pkgconfig(uuid)
BuildRequires : popt-dev
Patch1: clear-crash-patch.patch

%description
Signing tool for PE-COFF binaries, hopefully at least vaguely compliant with
the PE and Authenticode specifications.

%package bin
Summary: bin components for the pesign package.
Group: Binaries
Requires: pesign-libexec = %{version}-%{release}
Requires: pesign-license = %{version}-%{release}

%description bin
bin components for the pesign package.


%package doc
Summary: doc components for the pesign package.
Group: Documentation
Requires: pesign-man = %{version}-%{release}

%description doc
doc components for the pesign package.


%package libexec
Summary: libexec components for the pesign package.
Group: Default
Requires: pesign-license = %{version}-%{release}

%description libexec
libexec components for the pesign package.


%package license
Summary: license components for the pesign package.
Group: Default

%description license
license components for the pesign package.


%package man
Summary: man components for the pesign package.
Group: Default

%description man
man components for the pesign package.


%prep
%setup -q -n pesign-113
cd %{_builddir}/pesign-113
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1589854272
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -fzero-call-used-regs=used "
export FCFLAGS="$FFLAGS -fno-lto -fstack-protector-strong -fzero-call-used-regs=used "
export FFLAGS="$FFLAGS -fno-lto -fstack-protector-strong -fzero-call-used-regs=used "
export CXXFLAGS="$CXXFLAGS -fno-lto -fstack-protector-strong -fzero-call-used-regs=used "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1589854272
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pesign
cp %{_builddir}/pesign-113/COPYING %{buildroot}/usr/share/package-licenses/pesign/842745cb706f8f2126506f544492f7a80dbe29b3
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/authvar
/usr/bin/efikeygen
/usr/bin/efisiglist
/usr/bin/pesigcheck
/usr/bin/pesign
/usr/bin/pesign-client

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/pesign/*

%files libexec
%defattr(-,root,root,-)
/usr/libexec/pesign/pesign-authorize

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pesign/842745cb706f8f2126506f544492f7a80dbe29b3

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/authvar.1
/usr/share/man/man1/efikeygen.1
/usr/share/man/man1/efisiglist.1
/usr/share/man/man1/pesigcheck.1
/usr/share/man/man1/pesign-client.1
/usr/share/man/man1/pesign.1
